name: Run Benchmarks
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ] 

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
        
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Run All Benchmarks
        run: ./runAllJmh.sh

      - name: Deploy Merged Benchmark Results to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 016a70a392934d0e5a07a4d291731218
          file_path: merged-jmh-results/merged-jmh-results.json
          file_type: json

      - name: GH Pages Upload
        run: |
          git config --global user.name 'Joel Jeremy Marquez'
          git config --global user.email 'joeljeremy7@users.noreply.github.com'
          git add merged-jmh-results -f
          git commit -m "Updated Benchmark Results"
          git push origin `git subtree split --prefix merged-jmh-results main`:gh-pages --force